import { OutputChannel, window } from 'vscode';
import { Logger } from '../infrastructure/logger.js';
import { ApiService } from '../services/apiService.js';
import type { PullRequestPayload } from '../types/index.js';

export class GeneratePullRequestCommand {
  private readonly logger: Logger;
  private readonly outputChannel: OutputChannel;
  private readonly apiService: ApiService;

  constructor(logger: Logger, outputChannel: OutputChannel) {
    this.logger = logger;
    this.outputChannel = outputChannel;
    this.apiService = new ApiService(logger);
  }

  public async execute(): Promise<void> {
    this.logger.info('Executing Generate Pull Request command...');

    const editor = window.activeTextEditor;
    if (!editor) {
      this.logger.warn('No active text editor found');
      void window.showInformationMessage('No active text editor found');
      return;
    }

    const document = editor.document;
    const code = document.getText();
    const language = document.languageId;
    const fileName = document.fileName;

    this.outputChannel.appendLine(`[EcoLint] Generating Pull Request for ${language} code...`);
    this.outputChannel.appendLine(`File: ${fileName}`);
    this.outputChannel.appendLine('---');

    try {
      // First, run analysis and benchmark to get data for PR
      const [analysisResult, benchmarkResult] = await Promise.all([
        this.apiService.analyzeCode(code, language, fileName),
        this.apiService.runBenchmark(code, language, fileName),
      ]);

      if (!analysisResult.success || !benchmarkResult.success) {
        this.outputChannel.appendLine(`[EcoLint] Failed to gather data for PR`);
        this.logger.error('Failed to gather data for PR');
        return;
      }

      // Create PR payload
      const payload: PullRequestPayload = {
        title: `EcoLint: Optimize ${fileName}`,
        description: `Automated optimization PR generated by EcoLint`,
        analysisResults: analysisResult.data ? [analysisResult.data] : [],
        benchmarkResults: benchmarkResult.data ? [benchmarkResult.data] : [],
        optimizationResults: [],
        targetBranch: 'main',
        sourceBranch: 'ecolint/optimization',
      };

      const response = await this.apiService.generatePullRequest(payload);

      if (response.success && response.data) {
        this.outputChannel.appendLine(`[EcoLint] Pull Request created: ${response.data.prUrl}`);
        this.logger.info('Generate Pull Request command completed', { prUrl: response.data.prUrl });
      } else {
        this.outputChannel.appendLine(`[EcoLint] PR creation failed: ${response.error}`);
        this.logger.error('PR creation failed', response.error);
      }
    } catch (error) {
      this.logger.error('Pull Request generation failed', error);
      this.outputChannel.appendLine(`[EcoLint] Pull Request generation failed: ${error}`);
      throw error;
    }
  }
}